# configuration file for ${project.name} v${project.version}

# Localization language
language: en-US


# enabled worlds list
# if this list is empty, all worlds will be added to the enabled worlds list
# otherwise, only listed worlds will be added to the enabled worlds list

enabled-worlds:
#  - enabled_world1
#  - enabled_world2


# disabled worlds list
# these worlds will be removed from the enabled worlds list created by the previous setting

disabled-worlds:
  - disabled_world1
  - disabled_world2


# Use sound effects
sound-effects: true

# Protect chests from other players
chest-protection: true

# Allow player's killer to access death chest
killer-looting: false

# Require players to have a chest in their inventory
require-chest: false

# prevent placing items in death chests
prevent-item-placement: true

# deploy chests for players in creative mode
creative-deploy: false

# allow access to chests for players in creative mode
creative-access: false

# Distance from death location to search for a valid chest location
# NOTE: This checks exponentially more locations for each increase in distance
# For this reason, it is not recommended to set this value too high.
search-distance: 10

# Place chests above the void when players die below level 0
place-above-void: true

# Place chests below max build height when players die above max height
place-below-max: true

# Time in minutes before death chests expire. Set to 0 (zero) to disable chest expiration.
expire-time: 60

# Place sign on death chests
chest-signs: true

# Drop items that don't fit in death chest
allow-drops: true

# Allow quick-looting of chests with sneak-punch
quick-loot: true

# Automatically remove empty chests on closing
remove-empty: true

# number of DeathChests shown per page in list command
list-page-size: 5

# Check protection plugin permissions on death chest placement or access
# If a value is configured true, the protection plugin restrictions will be respected
# If a value is configured false, the protection plugin restrictions will be ignored
protection-plugins:
  Factions:
    check-on-place: true
    check-on-access: false

  GriefPrevention:
    check-on-place: true
    check-on-access: false

  PreciousStones:
    check-on-place: true
    check-on-access: false

  RoadBlock:
    check-on-place: true
    check-on-access: false

  Towny:
    check-on-place: true
    check-on-access: false

  WorldGuard:
    check-on-place: true
    check-on-access: false


# List of block materials that can be replaced by a chest
replaceable-blocks:
  - AIR
  - CAVE_AIR
  - GRASS
  - TALL_GRASS
  - SNOW
  - VINE
  - LILY_PAD
  - WATER
  - LAVA
