# This is the config file for ${project.name} v${project.version}

# Localization language
language: en-US

# Storage Type ( sqlite | yaml )
storage-type: sqlite

# Use sound effects
sound-effects: true


# Note: use only one enabled/disabled list, and comment out or remove the other
# enabled worlds list (use this list for a default-deny world policy)

#enabled-worlds:
#  - enabled_world1
#  - enabled_world2


# disabled worlds list (use this list for a default-allow world policy)

disabled-worlds:
  - disabled_world1
  - disabled_world2


# Protect chests from other players
chest-protection: true

# Allow player's killer to access death chest
killer-looting: false

# Require players to have a chest in their inventory
require-chest: false

# prevent placing items in death chests
prevent-item-placement: true

# deploy chests for players in creative mode
creative-deploy: false

# allow access to chests for players in creative mode
creative-access: false

# Distance from death location to search for a valid chest location
# NOTE: This checks exponentially more locations for each increase in distance
# For this reason, it is not recommended to set this value too high.
search-distance: 5

# Place chests above the void when players die below level 0
place-above-void: true

# Time in minutes before death chests expire. Set to 0 (zero) to disable chest expiration.
expire-time: 60

# Place sign on death chests
chest-signs: true

# Drop items that don't fit in death chest
allow-drops: true

# Allow quick-looting of chests with sneak-punch
quick-loot: true

# Automatically remove empty chests on closing
remove-empty: true

# Require build permission from protection plugins when deploying a chest
# If true, block place permission will be checked for each plugin on chest deployment
# If false, chest access permission will be checked for each plugin on chest deployment
require-build-permission: false

# Check protection plugin permissions on death chest placement or access
# If a value is configured true, the protection plugin restrictions will be respected
# If a value is configured false, the protection plugin restrictions will be ignored
protection-plugins:
  Factions:
    check-on-place: true
    check-on-access: false

  GriefPrevention:
    check-on-place: true
    check-on-access: false

  PreciousStones:
    check-on-place: true
    check-on-access: false

  ProClaim:
    check-on-place: true
    check-on-access: false

  RoadBlock:
    check-on-place: true
    check-on-access: false

  Towny:
    check-on-place: true
    check-on-access: false

  WorldGuard:
    check-on-place: true
    check-on-access: false


# List of blocks that can be replaced by a chest
replaceable-blocks:
  - AIR
  - LONG_GRASS
  - SNOW
  - VINE
  - WATER_LILY
  - WATER
  - STATIONARY_WATER
  - LAVA
  - STATIONARY_LAVA
