name: SavageDeathChest
main: com.winterhaven_mc.deathchest.DeathChestMain
author: Tim Savage
version: 1.0-beta
softdepend: [GriefPrevention,WorldGuard]

commands:
   deathchest:
      aliases: sdc
      description: This is the DeathChest command.
      permission: deathchest.reload
      permission-message: You don't have required permission <permission>.
      usage: |
        /<command> [subcommand]
        /<command> reload - Reloads the configuration file
        /<command> list - Lists all currently active death chests
      
permissions:
  deathchest.chest:
    description: Allows the creation of a death chest.
    default: true

  deathchest.loot:
    description: Allows player to quick-loot death chests by sneak-punching.
    default: true

  deathchest.loot.others:
    description: Allow player to quick-loot other player's chests.
    default: op

  deathchest.freechest:
    description: Overrides require chest in inventory configuration.
    default: op

  deathchest.doublechest:
    description: Allows placement of double chests if necessary.
    default: true

  deathchest.drops:
    description: Allows overflow items to drop on ground.
    default: true

  deathchest.reload:
    description: Allows reloading the config file.
    default: op

  deathchest.list:
    description: Allows listing all currently tracked DeathChest items.
    default: op

  deathchest.player:
    description: Default permissions.
    default: true
    children:
      deathchest.chest: true
      deathchest.loot: true
      deathchest.doublechest: true
      deathchest.drops: true

  deathchest.admin:
    description: Gives access to DeathChest admin commands.
    default: op
    children:
      deathchest.player: true
      deathchest.freechest: true
      deathchest.loot.others: true
      deathchest.reload: true
      deathchest.list: true
