name: ${project.name}
main: com.winterhaven_mc.deathchest.PluginMain
author: ${project.author}
version: ${project.version}
api-version: 1.13
softdepend: [Factions,GriefPrevention,Multiverse-Core,PreciousStones,ProClaim,RoadBlock,Towny,WorldGuard]

commands:
   deathchest:
      aliases: sdc
      description: This is the DeathChest command.
      permission: deathchest.admin
      permission-message: You don't have required permission <permission>.
      usage:
        /<command> reload - Reloads the configuration file
      
permissions:
  deathchest.chest:
    description: Allows the creation of a death chest.
    default: true

  deathchest.loot:
    description: Allows player to quick-loot death chests by sneak-punching.
    default: true

  deathchest.loot.killer:
    description: Allows player to loot death chests of players they have killed.
    default: true

  deathchest.loot.other:
    description: Allow player to quick-loot other player's chests.
    default: op

  deathchest.freechest:
    description: Overrides require chest in inventory configuration.
    default: op
    
  deathchest.creative-access:
    description: Overrides restriction on opening death chests in creative mode.
    default: op
    
  deathchest.allow-place:
    description: Overrides restriction on placing items in death chests.

  deathchest.doublechest:
    description: Allows placement of double chests if necessary.
    default: true

  deathchest.drops:
    description: Allows overflow items to drop on ground.
    default: true

  deathchest.reload:
    description: Allows reloading the config file.
    default: op

  deathchest.status:
    description: Allows viewing deathchest status.
    default: op

  deathchest.player:
    description: Default permissions.
    default: true
    children:
      deathchest.chest: true
      deathchest.loot: true
      deathchest.doublechest: true
      deathchest.drops: true

  deathchest.admin:
    description: Gives access to DeathChest admin commands.
    default: op
    children:
      deathchest.freechest: true
      deathchest.loot.other: true
      deathchest.creative-access: true
      deathchest.allow-place: true
      deathchest.reload: true
      deathchest.status: true
